enum ActionTypes {
  // Alert
  DISPLAY_ALERT = "DISPLAY_ALERT",
  CLEAR_ALERT = "CLEAR_ALERT",

  // Authentication
  REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN",
  REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS",
  REGISTER_USER_ERROR = "REGISTER_USER_ERROR",

  LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN",
  LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS",
  LOGIN_USER_ERROR = "LOGIN_USER_ERROR",
  LOGOUT_USER = "LOGOUT_USER",

  UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN",
  UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS",
  UPDATE_USER_ERROR = "UPDATE_USER_ERROR",

  TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR",

}

export default ActionTypes;
